repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--diff", "--color"]
        stages: [push]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        stages: [push]
      - id: end-of-file-fixer
        stages: [push]
      - id: check-yaml
        stages: [push]
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        skip: ["*/__init__.py"]
        stages: [push]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
        stages: [push]
      - id: ruff-format
        stages: [push]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.17.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: ["types-PyYAML"]
